name: Commit

on: workflow_dispatch

jobs:
  commit:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.TOKEN_ACTION }}

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TOKEN_ACTION }}
          persist-credentials: true
          submodule: true
      - run: git submodule update --init --recursive --remote --merge
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v7.2.0
        id: auto-commit-action #mandatory for the output to show up in ${{ steps }}
        with:
          commit_message: Updated. submodule 
