name: Commit

on: workflow_dispatch

jobs:
  commit:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.TOKEN_ACTION }}
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TOKEN_ACTION }}
          fetch-depth: 0
          submodules: recursive 
      - name: Setup Git user
        uses: fregante/setup-git-user@main
      - run: | 
            git submodule update --recursive --remote --merge
            git add .
            git commit -m "Updated submodule."
            git push
