name: Upstream

on: workflow_dispatch
jobs:
  upstream:
   runs-on: ubuntu-latest
   steps:
     - name: checkout
       uses: actions/checkout@main
       with:
         fetch-depth: 0
         submodules: true
     - name: Setup Git user
       uses: fregante/setup-git-user@v2.0.2
     - run: git remote add upstream https://github.com/PermPermPermit777/xash3d-fwgs
     - run: git fetch upstream
     - run: git merge --strategy-option theirs
     - run: |
          git add .
          git commit -m "merge"
          git push
  
