name: merge
on:
  workflow_dispatch:
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Merge staging -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: master
          commit_message: Merge backup into master
          github_token: ${{ secrets.GITHUB_TOKEN }}
