name: Submodule
on:
  workflow_dispatch:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with: 
          persist-credentials: false
          token: ${{ secrets.TOKEN_ACTION }}
          fetch-depth: 0
          submodules: recursive
      - name: update submodule
        run: git submodule update --init --recursive --remote --merge
      - uses: qoomon/actions--setup-git@v1.1.1
        env:
          token: ${{ secrets.TOKEN_ACTION }}
        with:
          user: bot

      - run: |
          git add .
          git commit -m "chore: update all submodule"
          git push origin master
